import { defineConfig } from 'rolldown'

export default defineConfig({
  input: [
    'src/index.ts',
    'src/zod.ts',
    'src/valibot.ts',
    'src/tanstack-db.ts',
    'src/pipe/index.ts',
    'src/sql/common.ts',
    'src/sql/pg.ts',
    'src/sql/sqlite.ts',
    'src/sql/types.ts',
    'src/core/index.ts',
    'src/core/order-by.ts',
    'src/core/schema.ts',
    'src/core/where.ts',
    'src/db0/pg.ts',
    'src/db0/sqlite.ts',
    'src/db0/types.ts',
    'src/drizzle/pg.ts',
    'src/drizzle/sqlite.ts',
    'src/kysely/fromKysely.ts',
    'src/kysely/pg.ts',
    'src/kysely/types.ts',
  ],
  output: {
    dir: 'dist',
    format: 'esm',
    preserveModules: true,
    preserveModulesRoot: 'src',
    entryFileNames: '[name].js',
  },
  platform: 'neutral',
  external: [
    'zod',
    'valibot',
    'drizzle-orm',
    'kysely',
    '@tanstack/db',
    /^drizzle-orm\//,
  ],
})